name: Test and Build

on:
  push:
    branch: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup python environment
        uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: install requirements
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: run tests
          run: |
            python manage.py test