name: Test and Build

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run tests
        env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL}}
        run: |
          python manage.py test